### ISSUE TITLE
401 - Unauthorized when clicking on "Edit Relations"

### ISSUE THREAD

**Issue by caveman69** [lars-erik/umbraco-relation-editor#11]
I have used the Relations Editor before so I know it works. 

I am running Umbraco 7.2.2 on this specific install. I am attempting to Edit Relations (my relationseditor.config is set and I get the item in the context menu). When I click "Edit Relations" I see the slide start to  happen for the UI to appear and then I go immediately to login screen.

I checked in debug tools and I am getting a 401 on this url:  /umbraco/relationseditor/relations/getrelations?parentId=24681&section=content&treeType=

That, obviously, redirects me to login page.

I set up Umbraco through VS 2013 using an Empty Web project, adding 7.2.2 through NuGet. I finished installation and checked everything worked properly. Then I installed the package and set up RelationsEditor.config.

Any ideas as to why this might be occurring?

Brice

**Comment by caveman69** [comment]
Sorry... Forgot to mention that I installed the package version 1.0.5142. I am trying to get to an install state of a previous installation so that I can switch db to an previous 7.2.2 db. I am still connected to the default db at this time, though.

I also created a "testRelation" For TextPage to BlogPost in Umbraco and my config looks like this:

```
<RelationEditor>
    <ObjectType Name="Document" Alias="TextPage">
        <EnabledRelation Alias="testRelation">
            <EnabledChildType Alias="BlogPost"/>
        </EnabledRelation>
    </ObjectType>
</RelationEditor>
```

**Comment by caveman69** [comment]
I upgraded to the most recent version and this problem went away.

Possibly the first install of the previous version did not complete successfully or there was some issue between it and 7.2.2.

**Comment by lars-erik** [comment]
There was an issue that was fixed by community members. :)
