### ISSUE TITLE
"object reference not set to an instance of an object" on document type creation  in back office

### ISSUE THREAD

**Issue by johnseto** [lars-erik/umbraco-relation-editor#14]
In the back office when you try and create document type within a document type folder, an except is raised. 

I have managed (with some help from my colleague) to step through the code and fixed it.

I will generate a pull-request once I have figured how to check in the code.

**Comment by lars-erik** [comment]
Thanks for the prompt report. :) Guess I should've tested that too.
I'd really like to get a fix for that out quickly, so I'll see if I can repro and fix.

**Comment by johnseto** [comment]
No problem. I'll edit the code within Git editor. 
BTW I'm the Chinese looking guy who was sat next to you in the keynote at CG16 :-)

**Comment by lars-erik** [comment]
👍 :)
Was nice saying hello! Thanks for helping.

**Comment by johnseto** [comment]
I think I've created a pull request correctly. :-)

**Comment by johnseto** [comment]
Thanks for merging 👍
