### ISSUE TITLE
Bug? Clicking Save adds duplicate relation(s).

### ISSUE THREAD

**Issue by s6admin** [lars-erik/umbraco-relation-editor#7]
Hi Erik,

Using the 1.0.5 tag.

We have two Documents (A and B) related by a single row in the Relations table. The relationship is Bidirectional. If we open the Editor action panel (on either A or B) the one relationship appears correctly. If we click SAVE without doing anything else a new duplicate relation is added to the table. Repeating the process continues to add more duplicates.

Here is our basic editor configuration:

[ObjectType Name="Document" Alias="A"]
   [EnabledRelation Alias="AToB"]
      [EnabledChildType Alias="B"/]
    [/EnabledRelation]
[/ObjectType]
[ObjectType Name="Document" Alias="B"]
    [EnabledRelation Alias="AToB"]
      [EnabledChildType Alias="A"/]
    [/EnabledRelation]
[/ObjectType]

Also wondering if there is a way to prevent multiple row entries for bidirectional relationships (where the the parent/child ids are reversed). Not sure if that is a default Umbraco behavior, though.

Thank you for your help!

**Comment by lars-erik** [comment]
Fixed in upcoming release.
