### ISSUE TITLE
Notfication registering breaking when relation editor is installed

### ISSUE THREAD

**Issue by philippjenni** [lars-erik/umbraco-relation-editor#8]
The releation editor register an action with Letter "R". "R" is already registered by umbraco "Permissions" action.

This raises an duplicated id execption when you will change the notifcation on a folder which has the relation action enabled

Problem testet with Umbraco 7.2.1

**Comment by lars-erik** [comment]
Fixed in upcoming release. Now use 0x1337 and 0x7331 for letters. :)
